### ISSUE TITLE
error KeyError: 'AUTHENTICATION_MODE'

### ISSUE THREAD

**Issue by peya02** [lipinght/PBIEmbedRLSFlaskSample#3]
Hello

It is giving me the following errors that I do not understand very well what they are due to

```
Traceback (most recent call last):
  File "C:\Flask\login_microsoft\FLASK-POWERBI\env\Lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Flask\login_microsoft\FLASK-POWERBI\env\Lib\site-packages\werkzeug\middleware\proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Flask\login_microsoft\FLASK-POWERBI\env\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Flask\login_microsoft\FLASK-POWERBI\env\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Flask\login_microsoft\FLASK-POWERBI\env\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request      
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Flask\login_microsoft\FLASK-POWERBI\env\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request      
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Flask\login_microsoft\FLASK-POWERBI\env\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Flask\login_microsoft\FLASK-POWERBI\app.py", line 169, in get_embed_info
    config_result = Utils.check_config(app)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Flask\login_microsoft\FLASK-POWERBI\utils.py", line 16, in check_config
    if app.config['AUTHENTICATION_MODE'] == '':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'AUTHENTICATION_MODE'
```

I log into the app with the user Microsoft Azure. I think it comes from the utils.py code part

```
@app.route('/getembedinfo', methods=['GET'])
def get_embed_info():
    '''Returns report embed configuration'''

    config_result = Utils.check_config(app)
    if config_result is not None:
        return json.dumps({'errorMsg': config_result}), 500
```

Might you help me?

**Comment by peya02** [comment]
It already worked for me.

**Comment by peya02** [comment]
It already worked for me.
